//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootSwitchApp_01.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"{0}\"")]
        public string FormatAuthFileName {
            get {
                return ((string)(this["FormatAuthFileName"]));
            }
            set {
                this["FormatAuthFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"auth\" \"{0}\"")]
        public string FormatAuthArguments {
            get {
                return ((string)(this["FormatAuthArguments"]));
            }
            set {
                this["FormatAuthArguments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"{0}\"")]
        public string FormatRegFileName {
            get {
                return ((string)(this["FormatRegFileName"]));
            }
            set {
                this["FormatRegFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"register\"\"{0}\" \"{1}\" \"{2}\"")]
        public string FormatRegArguments {
            get {
                return ((string)(this["FormatRegArguments"]));
            }
            set {
                this["FormatRegArguments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\User\\Documents\\MyProject\\FootSwitchApp-01\\NeoFace Cloud Type A サンプルC#アプリ" +
            "\\NeoFaceCloudSample\\bin\\Debug\\NeoFaceCloudSample.exe")]
        public string PathExe {
            get {
                return ((string)(this["PathExe"]));
            }
            set {
                this["PathExe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\User\\Documents\\MyProject\\FootSwitchApp-01\\FootSwitchApp-01\\bin\\Debug\\res" +
            "ult\\result_0.bmp")]
        public string PathImg {
            get {
                return ((string)(this["PathImg"]));
            }
            set {
                this["PathImg"] = value;
            }
        }
    }
}
